name: Update topic AI from URL

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update-topic-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Create topics directory if not exists
        run: mkdir -p topics

      - name: Fetch data from URL
        run: |
          curl -s https://tinyhref.com/launch/ai/readme -o topics/ai.md

      - name: Stash local changes before pull
        run: |
          git stash
          git pull --rebase origin main
          git stash pop

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add topics/ai.md
          git commit -m "🤖 auto-update" || exit 0
          git push --force origin main
